# Generated by Django 5.0.2 on 2024-02-24 18:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(db_column='tx_email', max_length=256, unique=True)),
                ('password', models.CharField(db_column='tx_password', max_length=104)),
                ('full_name', models.CharField(db_column='tx_name', max_length=256)),
                ('last_login', models.DateTimeField(blank=True, db_column='dt_last_login', null=True)),
                ('is_active', models.BooleanField(db_column='cs_active', default=True)),
                ('is_superuser', models.BooleanField(db_column='cs_superuser', default=False, null=True)),
                ('is_staff', models.BooleanField(db_column='cs_staff', default=False, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'tb_auth_user',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserAdress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adress', models.TextField(db_column='tx_adress', max_length=256, verbose_name='Adress')),
                ('city', models.CharField(db_column='tx_city', max_length=50, verbose_name='City')),
                ('country', models.CharField(db_column='tx_country', max_length=50, verbose_name='Country')),
                ('postal_code', models.CharField(db_column='tx_postal_code', max_length=20, verbose_name='Postal Code')),
                ('phone', models.CharField(db_column='tx_phone', max_length=20, verbose_name='Phone')),
                ('user', models.ForeignKey(db_column='id_user', db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='user_adresses', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'db_table': 'tb_adress',
                'managed': True,
            },
        ),
    ]
