# Generated by Django 5.0.2 on 2024-02-28 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='dt_created', null=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='dt_modified', null=True, verbose_name='Modified at')),
                ('is_active', models.BooleanField(db_column='cs_active', default=True, verbose_name='Active')),
                ('name', models.CharField(db_column='tx_name', max_length=50, verbose_name='Name')),
                ('description', models.TextField(blank=True, db_column='tx_description', null=True, verbose_name='Name')),
            ],
            options={
                'db_table': 'tb_product_category',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='dt_created', null=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='dt_modified', null=True, verbose_name='Modified at')),
                ('is_active', models.BooleanField(db_column='cs_active', default=True, verbose_name='Active')),
                ('name', models.CharField(db_column='tx_name', max_length=50, verbose_name='Name')),
                ('description', models.TextField(blank=True, db_column='tx_description', null=True, verbose_name='Description')),
                ('sku', models.CharField(db_column='tx_sku', max_length=100, verbose_name='Sku')),
                ('price', models.FloatField(db_column='nb_price', verbose_name='Price')),
                ('quantity', models.IntegerField(db_column='nb_quantity', verbose_name='Quantity')),
                ('category', models.ForeignKey(db_column='id_product_category', db_index=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='product_categories', to='core.productcategory', verbose_name='Product Category')),
            ],
            options={
                'db_table': 'tb_products',
                'managed': True,
            },
        ),
    ]
