# Generated by Django 5.0.2 on 2024-02-28 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_create_product_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='availability',
            field=models.CharField(blank=True, choices=[('A', 'Available'), ('U', 'Unavailable')], max_length=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, db_column='tx_sku', max_length=100, verbose_name='Sku'),
        ),
        migrations.CreateModel(
            name='ProductSubCategory',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='dt_created', null=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='dt_modified', null=True, verbose_name='Modified at')),
                ('is_active', models.BooleanField(db_column='cs_active', default=True, verbose_name='Active')),
                ('name', models.CharField(db_column='tx_name', max_length=50, verbose_name='Name')),
                ('description', models.TextField(blank=True, db_column='tx_description', null=True, verbose_name='Description')),
                ('parent_category', models.ForeignKey(db_column='id_parent_category', db_index=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategory_categories', to='core.productcategory', verbose_name='Parent Category')),
            ],
            options={
                'db_table': 'tb_products_subcategory',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(blank=True, db_column='id_product_subcategory', db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_subcategories', to='core.productsubcategory', verbose_name='Product Sub Category'),
        ),
    ]
