# Generated by Django 5.0.2 on 2024-02-28 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_create_brand_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.CharField(blank=True, db_column='tx_image_url', max_length=250, null=True, verbose_name='Image Url'),
        ),
    ]
