# Generated by Django 5.0.2 on 2024-02-28 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_create_img_url_field_in_productmodel_'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='description',
            field=models.TextField(blank=True, db_column='tx_description', null=True, verbose_name='Description'),
        ),
        migrations.AlterModelTable(
            name='brand',
            table='tb_brands',
        ),
        migrations.AlterModelTable(
            name='productcategory',
            table='tb_products_categories',
        ),
        migrations.AlterModelTable(
            name='productsubcategory',
            table='tb_products_sub_categories',
        ),
    ]
