# Generated by Django 5.0.2 on 2024-02-29 04:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_tables'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('PD', 'Paid'), ('WP', 'Waiting Payment'), ('RJ', 'Rejected')], default='WP', max_length=2, verbose_name='Order Status')),
                ('total_order_price', models.FloatField(blank=True, db_column='nb_total_order_price', null=True, verbose_name='Total Order Price')),
                ('items', models.ManyToManyField(related_name='order_products', to='core.product', verbose_name='Order Items')),
                ('user', models.ForeignKey(db_column='id_user', db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='user_orders', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'db_table': 'tb_orders',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='dt_created', null=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='dt_modified', null=True, verbose_name='Modified at')),
                ('is_active', models.BooleanField(db_column='cs_active', default=True, verbose_name='Active')),
                ('quantity', models.IntegerField(db_column='nb_quantity', default=1, verbose_name='Quantity')),
                ('ordered', models.BooleanField(db_column='cs_ordered', default=False, verbose_name='Ordered')),
                ('order_item_price', models.FloatField(blank=True, db_column='nb_order_item_price', null=True, verbose_name='Order Item Price')),
                ('product', models.ForeignKey(db_column='id_product', db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='ordem_item_product', to='core.product', verbose_name='Order Item Product')),
                ('user', models.ForeignKey(db_column='id_user', db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='user_order_items', to=settings.AUTH_USER_MODEL, verbose_name='User Order Items')),
            ],
            options={
                'db_table': 'tb_order_items',
                'managed': True,
            },
        ),
    ]
