# Generated by Django 5.0.2 on 2024-02-29 07:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_fix_mistake_on_order_orderitem_relation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(db_column='id_user', db_index=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_orders', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(db_column='id_product', db_index=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ordem_item_product', to='core.product', verbose_name='Order Item Product'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='user',
            field=models.ForeignKey(db_column='id_user', db_index=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_order_items', to=settings.AUTH_USER_MODEL, verbose_name='User Order Items'),
        ),
    ]
