# Generated by Django 5.0.2 on 2024-02-29 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_orderitem_product'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='orderitem',
            table='tb_orderitems',
        ),
    ]
